locations:
  bedroom:
    x: -2.73
    y: 0.13
    yaw: 2.93
  charging_station:
    x: 0
    y: 0
    yaw: 0
  kitchen:
    x: 0.42
    y: 2.26
    yaw: 0.75
  kitchen_counter:
    x: 4
    y: 2.5
    yaw: 0
  living room:
    x: 4.61
    y: -0.28
    yaw: 0.2
  medicine_cabinet:
    x: 1
    y: -3
    yaw: -1.57
  start:
    x: 0
    y: 0
    yaw: 0
patrol_waypoints:
- x: -2.73
  y: 0.09
  yaw: -2.86
- x: -2.17
  y: 2.38
  yaw: 1.58
- x: -0.95
  y: -2.8
  yaw: -1.62
- x: 4.61
  y: -0.28
  yaw: 2.56
