locations:
  kitchen_counter:
    x: 4.0
    y: 2.5
    yaw: 0.0
  medicine_cabinet:
    x: 1.0
    y: -3.0
    yaw: -1.57
  start:
    x: 0.0
    y: 0.0
    yaw: 0.0
  charging_station:
    x: 0.0
    y: 0.0
    yaw: 0.0
  living_room:
    x: 3.761
    y: -2.582
    yaw: 0.294
  kitchen:
    x: 2.163
    y: 2.707
    yaw: 1.563
  bedroom:
    x: -3.098
    y: 0.476
    yaw: 3.094
patrol_waypoints:
  - x: 3.761
    y: -2.582
    yaw: 0.294
  - x: 2.163
    y: 2.707
    yaw: 1.563
  - x: -3.098
    y: 0.476
    yaw: 3.094
